---
sudo: false
language: ruby
cache: bundler
rvm:
  - 3.3.4
before_install: gem install bundler -v 2.5.11
script:
  - (cd spec/dummy && bundle install)
  - (cd spec/dummy && RAILS_ENV=test bundle exec rails db:setup)
  - bundle exec rspec
