name: Ruby Gem

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4
        bundler: 2.5.11
        bundler-cache: true

    - name: Set up the test database
      run: |
        bundle install
        bundle exec rails db:setup
      working-directory: spec/dummy

    - name: Run tests
      run: bundle exec rspec

    - name: Publish to RubyGems
      if: github.event_name == 'push'
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
